#!/bin/sh
PNAME=audio
VER=`sed -n 's/Version: \(.*\)/\1/p' DESCRIPTION`
PDIR=`pwd`
rm -rf /tmp/${PNAME}
mkdir /tmp/${PNAME} && cp -r . /tmp/${PNAME} && \
cd /tmp && (find ${PNAME}/ -name .svn -or -name \*~ | xargs rm -rf) && \
rm -rf /tmp/${PNAME}/autom* /tmp/${PNAME}/a.out* /tmp/${PNAME}/config.* /tmp/${PNAME}/src/Makevars /tmp/${PNAME}/src/config.h /tmp/${PNAME}/mkdist && \
R CMD build ${PNAME} && cp ${PNAME}_${VER}.tar.gz "${PDIR}/../${PNAME}_${VER}.tar.gz"
cd "${PDIR}"
ls -l "../${PNAME}_${VER}.tar.gz"
